# 第 2 节　使用 Python 进行描述统计：多变量

## 第 3 章　使用 Pyhton 进行数据分析｜用 Python 动手学统计学



### 4. 多变量数据的管理

In [1]:
# 用于数值计算的库
import pandas as pd
import scipy as sp

# 设置浮点数打印精度
%precision 3

'%.3f'

### 5. 实现：求各分组的统计量

In [2]:
fish_multi = pd.read_csv("3-2-1-fish_multi.csv")
print(fish_multi)

  species  length
0       A       2
1       A       3
2       A       4
3       B       6
4       B       8
5       B      10


In [3]:
# 按鱼的种类计算
group = fish_multi.groupby("species")
print(group.mean())

         length
species        
A             3
B             8


In [6]:
group

In [4]:
print(group.std(ddof = 1))

         length
species        
A           1.0
B           2.0


In [7]:
group.describe()

length                                    
         count mean  std  min  25%  50%  75%   max
species                                           
A          3.0  3.0  1.0  2.0  2.5  3.0  3.5   4.0
B          3.0  8.0  2.0  6.0  7.0  8.0  9.0  10.0

### 6. 实现：列联表

In [8]:
shoes = pd.read_csv("3-2-2-shoes.csv")
print(shoes)

   store color  sales
0  tokyo  blue     10
1  tokyo   red     15
2  osaka  blue     13
3  osaka   red      9


In [9]:
cross = pd.pivot_table(
    data = shoes,
    values = "sales",
    aggfunc = "sum",
    index = "store",
    columns = "color"
)
print(cross)

color  blue  red
store           
osaka    13    9
tokyo    10   15


### 9. 实现：协方差

In [10]:
cov_data = pd.read_csv("3-2-3-cov.csv")
print(cov_data)

      x   y
0  18.5  34
1  18.7  39
2  19.1  41
3  19.7  38
4  21.5  45
5  21.7  41
6  21.8  52
7  22.0  44
8  23.4  44
9  23.8  49


In [11]:
# 读取数据的列
x = cov_data["x"]
y = cov_data["y"]

# 求样本容量
N = len(cov_data)

# 求各变量均值
mu_x = sp.mean(x)
mu_y = sp.mean(y)

c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  if __name__ == '__main__':
c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  # Remove the CWD from sys.path while we load stuff.


In [12]:
# 样本协方差
cov_sample = sum((x - mu_x) * (y - mu_y)) / N
cov_sample

6.906

In [13]:
# 协方差
cov = sum((x - mu_x) * (y - mu_y)) / (N - 1)
cov

7.673

### 10. 实现：协方差矩阵

In [14]:
# 样本协方差
sp.cov(x, y, ddof = 0)

c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: scipy.cov is deprecated and will be removed in SciPy 2.0.0, use numpy.cov instead
  


array([[ 3.282,  6.906],
       [ 6.906, 25.21 ]])

In [15]:
# 无偏协方差
sp.cov(x, y, ddof = 1)

c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: scipy.cov is deprecated and will be removed in SciPy 2.0.0, use numpy.cov instead
  


array([[ 3.646,  7.673],
       [ 7.673, 28.011]])

### 13. 实现：皮尔逊积矩相关系数

In [16]:
# 计算两个变量的方差
sigma_2_x = sp.var(x, ddof = 1)
sigma_2_y = sp.var(y, ddof = 1)

# 计算相关系数
rho = cov / sp.sqrt(sigma_2_x * sigma_2_y)
rho

c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  
c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  This is separate from the ipykernel package so we can avoid doing imports until
c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  


0.7592719041137088

In [17]:
# 计算两个变量的方差
sigma_2_x_sample = sp.var(x, ddof = 0)
sigma_2_y_sample = sp.var(y, ddof = 0)

# 计算相关系数
cov_sample / sp.sqrt(sigma_2_x_sample * sigma_2_y_sample)

c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  
c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  This is separate from the ipykernel package so we can avoid doing imports until
c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  


0.7592719041137087

In [18]:
# 相关矩阵
sp.corrcoef(x, y)

c:\Users\ZackChang\.conda\envs\statsbook36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: scipy.corrcoef is deprecated and will be removed in SciPy 2.0.0, use numpy.corrcoef instead
  


array([[1.   , 0.759],
       [0.759, 1.   ]])